// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeighUpBlazor.Server.Data;

namespace WeighUpBlazor.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210107200648_WeighInDeadlineModelAdd")]
    partial class WeighInDeadlineModelAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("int");

                    b.Property<decimal>("PlayInAmount")
                        .HasColumnType("money");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CompetitionId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.Contestant", b =>
                {
                    b.Property<int>("ContestantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContestantId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.WeighInDeadline", b =>
                {
                    b.Property<int>("WeighInDeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WeighInDeadlineId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("WeighInDeadlines");
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.WeightLog", b =>
                {
                    b.Property<int>("WeightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContestantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightMeasurement")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WeightLogId");

                    b.HasIndex("ContestantId");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.Contestant", b =>
                {
                    b.HasOne("WeighUpBlazor.Shared.Models.Competition", null)
                        .WithMany("Contestants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.WeighInDeadline", b =>
                {
                    b.HasOne("WeighUpBlazor.Shared.Models.Competition", null)
                        .WithMany("WeighInDeadlines")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.WeightLog", b =>
                {
                    b.HasOne("WeighUpBlazor.Shared.Models.Contestant", null)
                        .WithMany("WeightLogs")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.Competition", b =>
                {
                    b.Navigation("Contestants");

                    b.Navigation("WeighInDeadlines");
                });

            modelBuilder.Entity("WeighUpBlazor.Shared.Models.Contestant", b =>
                {
                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
